### ISSUE TITLE
make contact adding routine easier

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [amnesica/KryptEY#17]
simple: 

When a [KryptEY] public key is detected in the clipboard, the keyboard should disappear.

- have a handshake button
- a formatted handshake json message is sent
- user copies the message
- keyboard automatically detects it from clipboard
- promp for contact name appears
- end handshake message is sent with own public key
- user will copy and keyboard detects it

**Comment by serrq** [comment]
It needs a handle, like kryptei:npub...
