### ISSUE TITLE
redesign proposal

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [amnesica/KryptEY#18]
Hello, I found this app pretty damn good. Unfortunately, the UI is not good.

I made some quick example on how it could look like:

> [redesign.zip](https://github.com/amnesica/KryptEY/files/11582694/redesign.zip)

![redesign](https://github.com/amnesica/KryptEY/assets/45887282/17c23065-365b-4ecd-bea9-b6dee2db86b0)

Used Icons from:
> https://fonts.google.com/icons?selected=Material+Symbols+Outlined:contact_support:FILL@0;wght@400;GRAD@0;opsz@48&icon.platform=web&icon.query=chat

**Comment by amnesica** [comment]
@hp8wvvvgnj6asjm7 thanks for the suggestion. The "decrypt from" field is nice although the encrypted message is of no relevance anymore if the message gets copied

**Comment by Wjxfi** [comment]
Cool idea
