### ISSUE TITLE
add release on f-droid

### ISSUE THREAD

**Issue by c33s** [amnesica/KryptEY#19]
cool thing that the app is available via izzy. any chance to also see it on the official f-droid repo?

**Comment by amnesica** [comment]
Hi @c33s, will be available in a few days. Will add a link in the README once its available

**Comment by amnesica** [comment]
Added link to F-Droid in README

**Comment by c33s** [comment]
thank you very much :D

**Comment by IzzySoft** [comment]
@amnesica congrats to the F-Droid listing! I see your Readme now carries both badges; I take it that means you want me to keep your app in my repo? As it's a reproducible build, that can be done without causing confusion. But to make sure, I thought I ask first before I mark it "keep" :wink: So shall I keep it?

**Comment by IzzySoft** [comment]
@amnesica ^^ guess the same procedure as with ClearClipboard then?

**Comment by amnesica** [comment]
@IzzySoft yes, exactly :)

**Comment by IzzySoft** [comment]
Thanks, marker set then :smile:
